version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE: loan-service
    # for development only
    command: npm run dev
    volumes:
      - ./services/loan-service:/app
      - /app/node_modules
    ports:
      - "5050:5050"
    depends_on:
      db:
        condition: service_healthy
    # development env
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: adi-loan
      emailUser: your-user
      emailPass: your-pass
  db:
    image: postgres:15
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data/
      - ./postgres/initdb:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: adi-loan
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d adi-loan"]
      interval: 10s
